create or replace view vw_indicator_values as
select indicator_values.id,
       indicator_values.ticker,
       indicator_values.value,
       indicator_values.period_id,
       periods.name as period_name,
       periods.type as period_type,
       periods.begin_dtm as period_begin_dtm,
       periods.end_dtm as period_end_dtm,
       indicator_values.indicator_link_id,
       vw_indicators_link.indicator_group_id,
       vw_indicators_link.indicator_group_name,
       vw_indicators_link.indicator_id,
       vw_indicators_link.indicator_name,
       vw_indicators_link.indicator_name_rus,
       vw_indicators_link.indicator_priority,
       vw_indicators_link.indicator_type_id,
       vw_indicators_link.indicator_type_name,
       vw_indicators_link.indicator_type_priority,
       vw_indicators_link.dimention_link_id,
       vw_indicators_link.dimention_id,
       vw_indicators_link.dimention_name,
       vw_indicators_link.dimention_short_name,
       vw_indicators_link.multiplier_id,
       vw_indicators_link.multiplier_name,
       vw_indicators_link.multiplier_multiplier,
       vw_indicators_link.multiplier_description
from indicator_values inner join vw_indicators_link on (indicator_values.indicator_link_id = vw_indicators_link.id) inner join
     periods on (indicator_values.period_id = periods.id) inner join
     enterprises on (indicator_values.ticker = enterprises.ticker);
